import { Footer } from '@/shared/components/footer'
import Header from '@/shared/components/header'
import { Metadata } from 'next'
import NextTopLoader from 'nextjs-toploader' // Импортируем компонент NextTopLoader для отображения индикатора загрузки.
import { Suspense } from 'react'
import './globals.css'
import ProvidersStore from './providerStore'

export const metadata: Metadata = {
	title: 'Инженеры | Главная',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<head>
				<link
					rel='stylesheet'
					href='https://fonts.googleapis.com/icon?family=Material+Icons'
				/>
			</head>
			<body>
				<Suspense>
					<ProvidersStore>
						<Header />
						{children}
						<Footer />
					</ProvidersStore>
				</Suspense>
				{/* Рендерим NextTopLoader для отображения индикатора загрузки. */}
				<NextTopLoader />
			</body>
		</html>
	)
}
